version: '2'
services:
  client:
    restart: always
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    restart: always
    build: ./server
    ports:
      - '5000:5000'
  